# Generated by Django 5.1.3 on 2024-11-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticlesModelEN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=50, verbose_name="Name"),
                ),
                (
                    "anons",
                    models.CharField(
                        default="", max_length=250, verbose_name="Announcement"
                    ),
                ),
                ("full_text", models.TextField(verbose_name="Article")),
                ("data", models.DateTimeField(verbose_name="Publication date")),
            ],
            options={
                "verbose_name": "New",
                "verbose_name_plural": "News",
            },
        ),
        migrations.CreateModel(
            name="ArticlesModelRU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=50, verbose_name="Название"
                    ),
                ),
                (
                    "anons",
                    models.CharField(default="", max_length=250, verbose_name="Анонс"),
                ),
                ("full_text", models.TextField(verbose_name="Статья")),
                ("data", models.DateTimeField(verbose_name="Дата публикации")),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.CreateModel(
            name="ArticlesModelUZ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=50, verbose_name="Ism"),
                ),
                (
                    "anons",
                    models.CharField(default="", max_length=250, verbose_name="E'lon"),
                ),
                ("full_text", models.TextField(verbose_name="Maqola")),
                ("data", models.DateTimeField(verbose_name="Nashr qilingan sana")),
            ],
            options={
                "verbose_name": "Yangiliklar",
                "verbose_name_plural": "Yangiliklar",
            },
        ),
    ]
